### ISSUE TITLE
Use latest version of appdmg

### ISSUE THREAD

**Issue by amsoell** [Aluxian/gulp-appdmg#1]
I noticed this module uses a pretty old version of appdmg. I'm running a project that uses some newer features, and when I updated the `package.json` file to use appdmg^0.4.5 everything ran perfectly. Any objections to updating this package to use that version? Happy to submit a pull request if you like, but it's literally a one-line change.

**Comment by aluxian** [comment]
Oh damn, haha, I've just realised... I'm using gulp-appdmg in another project of mine and I was actually wondering myself why appdmg hadn't updated in a while... I totally forgot this module is mine. I'm updating it right now.

**Comment by aluxian** [comment]
Done! Also published to npm. I took your word that it runs perfectly and didn't test it yet.

**Comment by amsoell** [comment]
Fantastic, thanks!
